---
- name: Install NTP packages
  ansible.builtin.package:
    name: ntp
    state: present

- name: Copy configurations file
  ansible.builtin.template:
    src: ntp.conf.j2
    dest: "/etc/ntp.conf"
  notify: Restart NTP

- name: Ensure NTP is enabled on boot
  ansible.builtin.service:
    name: ntp
    state: started
    enabled: true
